// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyyfllijtihtzdcqchaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5eWZsbGlqdGlodHpkY3FjaGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNDAxNjYsImV4cCI6MjA3MTgxNjE2Nn0._UTdlMaFX4c4f5mL1TdpElzYPUkX-X7DCWXfZw2WTfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});